spring:
  profiles:
    active:
      -dev
---
spring:
  profiles: dev
  application:
      name: microservice-config-dev-1
---
spring:
  profiles: pre
  application:
      name: microservice-config-pre