spring:
  profiles: dev
  application:
      name: microservice-config-dev
server:
  port: 8762                    # 指定该Eureka实例的端口
eureka:
  instance:
    hostname: eurekaservice-config
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/
---
spring:
  profiles: pre
  application:
      name: microservice-config-pre
server:
  port: 8763                    # 指定该Eureka实例的端口
eureka:
  instance:
    hostname: eurekaservice-config
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8763/eureka/