spring:
  profiles: dev
  application:
      name: microservice-config-dev
server:
  port: '{cipher}4533eae652d8a7aa4ec6e6bc17b35903e57d291a1f2f45f79b2bb3caaa4a80e0eb7c'    # 指定该Eureka实例的端口,同时测试一下加密
eureka:
  instance:
    hostname: eurekaservice-config
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
---
spring:
  profiles: pre
  application:
      name: microservice-config-pre
server:
  port: 8763                    # 指定该Eureka实例的端口
eureka:
  instance:
    hostname: eurekaservice-config
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/